### ISSUE TITLE
nil pointer panic with hmc v0.0.5

### ISSUE THREAD

**Issue by soerenschneider** [Mirantis/hmc#799]
After installing hmc version v0.0.5 via GitOps, I'm facing nil pointer panics that make the controller end up in crash loop backoff.

> panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x19617b0]
goroutine 251 [running]:
[github.com/Mirantis/hmc/internal/telemetry.(*Tracker).trackManagedClusterHeartbeat(0x400028f9a0](http://github.com/Mirantis/hmc/internal/telemetry.(*Tracker).trackManagedClusterHeartbeat(0x400028f9a0), {0x248bb78, 0x40006322d0})
	/workspace/internal/telemetry/tracker.go:94 +0x350
[github.com/Mirantis/hmc/internal/telemetry.(*Tracker).Tick(0x400028f9a0](http://github.com/Mirantis/hmc/internal/telemetry.(*Tracker).Tick(0x400028f9a0), {0x248bb78, 0x40006322d0})
	/workspace/internal/telemetry/tracker.go:54 +0xf8
[github.com/Mirantis/hmc/internal/telemetry.(*Tracker).Start(0x400028f9a0](http://github.com/Mirantis/hmc/internal/telemetry.(*Tracker).Start(0x400028f9a0), {0x248bb78, 0x40006322d0})
	/workspace/internal/telemetry/tracker.go:42 +0x44
[sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1(0x400028f9c0)](http://sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1(0x400028f9c0))
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/manager/runnable_group.go:226 +0xd0
created by [sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile](http://sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile) in goroutine 244
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/manager/runnable_group.go:210 +0x204

I guess the problem was introduced with commit `4822e0fa`. The repo that was used to install hmc is found [here](https://github.com/soerenschneider/hmc-flux-example).

**Comment by soerenschneider** [comment]
Apparently it has already been fixed with [#798](https://github.com/Mirantis/hmc/pull/798), thanks!
